# ===== STAGE 1: Build =====
FROM golang:1.24-alpine3.20 AS builder
RUN apk add --no-cache git ca-certificates \
    && update-ca-certificates

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
ENV CGO_ENABLED=0
RUN go build -o gateway ./cmd/server/main.go

# ===== STAGE 2: Runtime =====
FROM alpine:3.20
RUN apk add --no-cache ca-certificates \
    && update-ca-certificates
WORKDIR /root/
COPY --from=builder /app/gateway ./
COPY --from=builder /app/cmd/server/theta_scan.csv .
COPY --from=builder /app/cmd/server/tau_scan.csv .

# expose port yang benar
EXPOSE 8081

ENTRYPOINT ["./gateway"]
