# ===== STAGE 1: Build =====
FROM golang:1.24-alpine3.20 AS builder
RUN apk add --no-cache git ca-certificates \
    && update-ca-certificates

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
ENV CGO_ENABLED=0
RUN go build -o gateway ./cmd/server/main.go

# ===== STAGE 2: Runtime =====
FROM alpine:3.20
# Install certificates and timezone data
RUN apk add --no-cache ca-certificates tzdata \
    && update-ca-certificates \
    # Set container timezone to Asia/Jakarta (WIB)
    && cp /usr/share/zoneinfo/Asia/Jakarta /etc/localtime \
    && echo "Asia/Jakarta" > /etc/timezone

# Ensure Go logs use the correct timezone
ENV TZ=Asia/Jakarta

WORKDIR /root/
COPY --from=builder /app/gateway ./
COPY --from=builder /app/cmd/server/theta_scan.csv .
COPY --from=builder /app/cmd/server/tau_scan.csv .

# expose port yang benar
EXPOSE 8081

ENTRYPOINT ["./gateway"]
